### ISSUE TITLE
Machine Capability Database?

### ISSUE THREAD

**Issue by claypipe** [inkstitch/inkstitch#599]
Is there a database or wiki page anywhere that details the capabilities and incompatibilities of the various brands of embroidery machines when combined with InkStitch?

If not, would it be useful?

**Comment by lexelby** [comment]
There is not, and that could be useful.  It's primarily going to boil down to these facets:

1. What file formats does the machine support, and does Ink/Stitch support them?
2. What features does the machine support? Trims and color changes, primarily.

**Comment by kaalleen** [comment]
Same topic was discussed in #407 and some machines were already mentioned.
Should I create a starting point for this list on the Ink/Stitch website?
I don't know a lot of machines though and couldn't fill the list with information.
I would need help to create the list itself.

**Comment by lexelby** [comment]
I'm in favor!

**Comment by claypipe** [comment]
Another vote for it - If you do create one please can it have a plaintext field where features/problems can be described.

**Comment by kaalleen** [comment]
Ok, this could serve as a starting point: https://inkstitch.org/docs/machine-database/

Data structure looks as follows:
```
machine-database:
  - brand: Janome
    machines:
    - name: Memory Craft 400E
      file-formats: JEF, DST
      features: TRIM
      comments: Das ist ein Test. Kommentare, Kommentare!
```
There is no sorting at this point, but it wouldn't be a problem to do so.

What do you think?
